Todoappproject/Todoappproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from Todoappproject import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Todoappproject/todoapp/urls.py
from . import views
from django.urls import path

app_name = 'todoapp'

urlpatterns = [

    # function type views URL
    path('',views.home, name='home'),
    path('details', views.details, name='details'),
    path('delete/ <int:taskid>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),

    #class type views URL

    path('cbvlist/', views.TaskLiseView.as_view(), name='cbvlist'),
    path('cbvdetail/<int:pk>/', views.TaskDetailView.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.TaskUpdateView.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeleteview.as_view(), name = 'cbvdelete')

]

Todoappproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    desc=models.CharField(max_length=300)
    date=models.DateField()

    def __str__(self):
        return self.name

Todoappproject/todoapp/forms.py
from django import forms
from .models import Task

class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'date', 'priority', 'desc']

Todoappproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Task
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView

# Create your views here.

#class based Views

class TaskLiseView(ListView):
    model = Task
    template_name = 'cbvhome.html'
    context_object_name = 'task'

class TaskDetailView(DetailView):
    model = Task
    template_name = 'cbvdetail.html'
    content_object_name = 'task'

class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'cbvupdate.html'
    content_object_name = 'task'
    fields = ('name', 'priority', 'date', 'desc')

    
    def get_success_url(self):
        return reverse_lazy ('cbvdetail', kwargs= {'pk': self.get_object.id})

class TaskDeleteview(DeleteView):
    model = Task
    template_name = 'cbvdelete.html'
    
    def get_success_url(self):
        return reverse_lazy ('cbvlist')


#function based views
def home(request):
    task=Task.objects.all()
    if request.method=='POST':
        #collect data from the input field
        name=request.POST.get('Task','')
        #collect data from the input field
        priority=request.POST.get('priority','')
        #collect data from the input field
        desc=request.POST.get('desc','')
        #collect data from the input filed
        date=request.POST.get('date', '')
        #saving datat to a veriable
        task1=Task(name=name,priority=priority,desc=desc, date=date)
        task1.save()
    return render(request, 'home.html',{'task': task})

def details(request):
    #saving datat to a veriable from database
    task=Task.objects.all()

    return render(request, 'details.html', {'task': task})


def delete (request, taskid):
    task=Task.objects.get(id=taskid)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')

def update(request, id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render (request, 'update.html',{'f':f, 'task':task})

Todoappproject/todoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'img/logo.jpg' %}">
    <title>TODO LIST</title>
    
</head>
<body class="body">
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="#">HOME</a>
        <a href="#">ABOUT</a> -->
    <!-- </nav> -->
    <!-- <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="banner">
                    <div class="banner-text">
                        <a href="#"><h5>Todo Details</h5></a>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <!-- <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="banner-1">
                    <div class="banner-text">
                        <h3 name="hi">Todo Details</h3>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="banner-1">
                    <div class="banner-text">
                        <div class="split left">
                            <!-- <img src="{% static 'img/logo.jpg' %}" alt="Logo" class="title-logo"> -->
                        </div>
                        <div class="split right">
                            <h3 class="text-center custom_head">TODO LIST</h3>
                            <p class="text-center custom_text">Remember Your Daily Work !!!!!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        {% block content %}
        {% endblock %}
        {% include 'footer.html' %}

    
</body>
</html>

Todoappproject/todoapp/templates/cbvdelete.html
<style>
    .dele{
    margin-left: 50px;
    }
</style>

{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <p class="dele">Are Complete the Task </p>
    <button type="submit" class="dele">Confirm</button>
</form>
{% endblock %}

Todoappproject/todoapp/templates/cbvdetail.html
{% extends 'base.html' %}
{% block content %}

<h1>CLASS BASED DETAIL VIEW</h1>


<ul>
    <li>{{task.name}}
        {{task.priority}} <br>
        {{task.date}} <br>
        {{task.desc}}<br> </li>
</ul>

{% endblock %}

Todoappproject/todoapp/templates/cbvhome.html
{% extends 'base.html' %}
{% block content %}
<style>
    form{
        margin-top: 10px;
    }
    .priority{
    color: red;
    
    }
</style>
<h1>CLASS BASED VIEWS PAGE</h1>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form action="" method="POST" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="Task" id="" placeholder="Task Name">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="priority" id="" placeholder="priority">
                </div>
                <div class="form-group">
                    <input type="date" class="form-control" name="date" >
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="desc" placeholder="Detail Description">
                </div>      
                <input type="submit" name="submit" class="btn btn-success">
            </form>
            
            {{i.name}}
            {{i.priority}}<br>
            {{i.date}}<br>
            {{i.desc}}
            
        </div>
        <div class="col-md-6">
            <h4 style="justify-content: center;">TASK TO BE COMPLETED</h4>
            {% for i in task %}
            <div class="shadow card">
                <div class="card-body">
                  <h5 class="card-title">{{i.name}}</h5>
                  <p>{{i.date}}</p>
                  <p class="priority">{{i.priority}}</p>
                  <p>{{i.desc}}</p>
                  <a href="{% url 'delete' i.id %}" class="btn btn-danger">Done</a>
                  <a href="{% url 'update' i.id %}" class="btn btn-success">Update</a>
                  <a href="{%url 'details' %}" class="card-link">All Todo List View</a>
                  <!-- <a href="#" class="card-link">Another link</a> -->
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

Todoappproject/todoapp/templates/cbvupdate.html
{% extends 'base.html' %}
{% block content %}

<div class="shadow card">
    <div class="card-body">
        <h5 class="card-title">CLASS UPDATE VIEW</h5>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
        </form>
      <button type="submit">Confirm</button>

{% endblock %}

Todoappproject/todoapp/templates/delete.html
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <p class="dele">Are Complete the Task ?</p>
    <button type="submit" class="dele">Confirm</button>
</form>
{% endblock %}

Todoappproject/todoapp/templates/details.html
{% extends 'base.html' %}
{% block content %}

{% for i in task %}
<ul>
    <li>
        <b>Task Name :</b> {{i.name}} <br>
        <b>Priority :</b> {{i.priority}} <br>
        <b>Date :</b> {{i.date}} <br>
        <b>Description :</b> {{i.desc}}<br> 
    </li>
</ul>
{% endfor %}

<a href="{% url 'todoapp:home' %}">Return To Home</a>


{% endblock %}

Todoappproject/todoapp/templates/footer.html
<div class="footer navbar-fixed-bottom text-center my_footer">
    <p class="text-center">&copy; Copyrights 2024 - TodoApp Test 
</div>

Todoappproject/todoapp/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <p>Click<a href="{%url 'todoapp:details' %}"> here </a>for view all Tasks. </p>
    <div class="row">
        <div class="col-md-6">
            
            <div class="card mb-6">
                
                <h4 class="card-header text-center">CREATE NEW TASK HERE !</h4>
                <div class="form-container shadow p-3">
                    <form method="post" action="" class="row">
                        {% csrf_token %}
                        <div class="form-group col-md-6">
                            <label for="task">Task : </label>
                            <input type="text" class="form-control" id="Task" name="Task" placeholder="Task Name" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="priority">Priority:</label>
                            <input type="text" class="form-control" name="priority" id="" placeholder="Priority">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="task">Task Date:</label>
                            <input type="date" class="form-control" id="task_date" name="date" required>
                        </div>

                        <div class="form-group col-md-12 text-center mt-2 cust_button">
                            <input type="submit" name="submit" class="btn btn-success">
                        <!-- </div>
                        <div class="form-group col-md-12 text-center mt-2"> -->
                            <input type="reset" name="" class="btn btn-danger">
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card mb-6">
                <h4 class="card-header text-center">TASK TO BE COMPLETED</h4>
                <br>
                {% for i in task %}
                <div class="shadow card">
                    <div class="card-body">
                      <h5 class="card-title">Task Name : {{i.name}}</h5>
                      <p>Task End Date : {{i.date}}</p>
                      <p class="priority">Priority : {{i.priority}}</p>
                      <!-- <p>{{i.desc}}</p> -->
                      <a href="{% url 'todoapp:update' i.id %}" class="btn btn-primary">Update Task</a>
                      <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-success">Completed</a>
                      
                      
                      <!-- <a href="#" class="card-link">Another link</a> -->
                    </div>
                    {% endfor %}
                </div>
<!--                    <a href="#" class="btn btn-primary">Done</a>-->

                    <!-- Add 'btn btn-success' class for the update button to make it green -->
                    <!-- <button class="link-button btn btn-success" onclick="window.location='/task/23/update/'">Update Task</button> -->

                    <!-- Add 'btn btn-danger' class for the delete button to make it red -->
                    <!-- <button class="link-button btn btn-danger" onclick="window.location='/task_delete/23/'">Delete Task</button> -->


                </div>
                
            </div>
        </div>
    </div>
</div>

</div>

{% endblock %}

Todoappproject/todoapp/templates/test.html
{% extends 'base.html' %}
{% block content %}



<div class="container">
    <div class="row">

    <div class="col-md-6">
        <div class="card mb-6 form_container">
            <div class="card-header text-center">
                <h4>CREATE NEW TASK</h4>
            </div>            
            <form action="" method="POST" class="shadow p-3">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="" id="" placeholder="Task Name">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="priority" id="" placeholder="priority">
                </div>
                <div class="form-group">
                    <input type="date" class="form-control" name="date" >
                </div>
                <!-- <div class="form-group">
                    <input type="text" class="form-control" name="desc" placeholder="Detail Description">
                </div>       -->
                <input type="submit" name="submit" class="btn btn-success">
            </form>
        

            
        </div>
        <div class="col-md-6">
        <div class="card mb-6">
            <h4 style="justify-content: center;">TASK TO BE COMPLETED</h4>
            {% for i in task %}
            <div class="shadow card">
                <div class="card-body">
                  <h5 class="card-title">{{i.name}}</h5>
                  <p>{{i.date}}</p>
                  <p class="priority">{{i.priority}}</p>
                  <p>{{i.desc}}</p>
                  <a href="{% url 'delete' i.id %}" class="btn btn-danger">Done</a>
                  <a href="{% url 'update' i.id %}" class="btn btn-success">Update</a>
                  <a href="{%url 'details' %}" class="card-link">All Todo List View</a>
                  <!-- <a href="#" class="card-link">Another link</a> -->
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>
</div>


<!-- </div> -->

{% endblock %}

Todoappproject/todoapp/templates/update.html
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <input type="submit" name="submit" class="btn btn-success">
</form>

<p class="p_deatail">* Please not that the details shown in table (model) name. Plese fill it carefully.</p>
{% endblock %}